version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - graphql-server

  graphql-server:
    build: ./graphql-server
    ports:
      - "9000:9000"
    environment:
      PORT: 9000

  recommender:
    build: ./recommender
    ports:
      - "6000:6000"
    environment:
      PORT: 6000

  external-apis:
    build: ./external-apis
    ports:
      - "7000:7000"
    environment:
      PORT: 7000

  core:
    build: ./core
    ports:
      - "8000:8000"
    depends_on:
      - external-apis
      - recommender
    environment:
      PORT: 8000
#docker-compose up --build
#docker-compose up -d --build
#docker-compose down
